---
apiVersion: v1
kind: Service
metadata:
  name: myflask
spec:
  selector:
    app: myflask
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
spec:
  selector:
    matchLabels:
      app: myflask
  replicas: 4
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
      - name: myflask
        image: mushdavtyan/myflaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
