apiVersion: v1
kind: Namespace
metadata:
   name: balance-test
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flaskold
  namespace: balance-test
  labels:
    app: flaskold
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskold
  template:
    metadata:
      labels:
        app: flaskold
    spec:
      containers:
      - name: flaskold
        image: mushdavtyan/myflaskapp:3.6
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask100
  namespace: balance-test
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask100
        image: mushdavtyan/myflaskapp100:3.6
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask800
  namespace: balance-test
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask800
        image: mushdavtyan/myflaskapp800:3.6
---
apiVersion: v1
kind: Service
metadata:
  name: flaskold
  namespace: balance-test
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: flaskold
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: balance-test
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: flask
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: balance-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/websocket-services: "node-socket-service"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/load-balance: "ewma"
spec:
  rules:
  - http:
      paths:
        - path: /stats
          backend:
            serviceName: flask
            servicePort: 8001
        - path: /static
          backend:
            serviceName: flask
            servicePort: 8001
        - path: /
          backend:
            serviceName: flaskold
            servicePort: 8001
        - path: /stats800
          backend:
            serviceName: flask
            servicePort: 8001
        - path: /stats100
          backend:
            serviceName: flask
            servicePort: 8001
